package com.quicksolveplus.qspmobile.schedule.models

import com.google.gson.annotations.SerializedName

data class SchedulesItem(
    @SerializedName("AddNewLinkedClient") val addNewLinkedClient: Boolean,
    @SerializedName("AllowMoreThanOneEmployeeToSchedule") val allowMoreThanOneEmployeeToSchedule: Boolean,
    @SerializedName("BackgroundColor") val backgroundColor: String?,
    @SerializedName("ClientAddress1") val clientAddress1: String,
    @SerializedName("ClientAddress2") val clientAddress2: String,
    @SerializedName("ClientApplyClock") val clientApplyClock: Int,
    @SerializedName("ClientCellPhone") val clientCellPhone: String,
    @SerializedName("ClientCity") val clientCity: String,
    @SerializedName("ClientFirstName") val clientFirstName: String,
    @SerializedName("ClientHomePhone") val clientHomePhone: String,
    @SerializedName("ClientLastName") val clientLastName: String,
    @SerializedName("ClientLinkFirstName") val clientLinkFirstName: Any,
    @SerializedName("ClientLinkLastName") val clientLinkLastName: Any,
    @SerializedName("ClientLinkUID") val clientLinkUID: Int,
    @SerializedName("ClientNickName") val clientNickName: String,
    @SerializedName("ClientOtherPhone") val clientOtherPhone: String,
    @SerializedName("ClientProfilePic") val clientProfilePic: String,
    @SerializedName("ClientShiftName") val clientShiftName: Any,
    @SerializedName("ClientState") val clientState: String,
    @SerializedName("ClientUID") val clientUID: Int,
    @SerializedName("ClientZip") val clientZip: String,
    @SerializedName("ClockIn") val clockIn: String,
    @SerializedName("ClockInImageFileName") val clockInImageFileName: Any,
    @SerializedName("ClockInLatitude") val clockInLatitude: String,
    @SerializedName("ClockInLongitude") val clockInLongitude: String,
    @SerializedName("ClockOut") val clockOut: String,
    @SerializedName("ClockOutImageFileName") val clockOutImageFileName: Any,
    @SerializedName("ClockOutLatitude") val clockOutLatitude: String,
    @SerializedName("ClockOutLongitude") val clockOutLongitude: String,
    @SerializedName("ClockShiftReason") val clockShiftReason: String,
    @SerializedName("Comments") val comments: String,
    @SerializedName("Create_DateTime") val createDateTime: Any,
    @SerializedName("Create_UserUID") val createUserUID: Int,
    @SerializedName("CurrentTime") val currentTime: String,
    @SerializedName("dDay") val dDay: Int,
    @SerializedName("dMonth") val dMonth: Int,
    @SerializedName("dYear") val dYear: Int,
    @SerializedName("DailyHours") val dailyHours: Any,
    @SerializedName("DoubletimeHours") val doubletimeHours: Any,
    @SerializedName("DsnStatus") val dsnStatus: String,
    @SerializedName("EVVChangeReason") val eVVChangeReason: Any,
    @SerializedName("EVVChangeReasonNote") val eVVChangeReasonNote: Any,
    @SerializedName("EVVClockInLocation") val eVVClockInLocation: Any,
    @SerializedName("EVVClockOutLocation") val eVVClockOutLocation: Any,
    @SerializedName("EndTime") val endTime: String,
    @SerializedName("EndTimeActual") val endTimeActual: String,
    @SerializedName("ForegroundColor") val foregroundColor: String,
    @SerializedName("HasMealBreak") val hasMealBreak: Int,
    @SerializedName("HasObjectives") val hasObjectives: Boolean,
    @SerializedName("HasSubCodes") val hasSubCodes: Boolean,
    @SerializedName("HolidayHours") val holidayHours: Any,
    @SerializedName("Hours") val hours: Double,
    @SerializedName("IHSSHours") val iHSSHours: Double,
    @SerializedName("IsApprovedBySupervisor") val isApprovedBySupervisor: Int,
    @SerializedName("IsCorrect") val isCorrect: String,
    @SerializedName("IsCustomEvent") val isCustomEvent: Boolean,
    @SerializedName("IsDsnComplete") val isDsnComplete: Boolean,
    @SerializedName("IsEVVUploaded") val isEVVUploaded: Boolean,
    @SerializedName("IsRequestReviewByEmployee") val isRequestReviewByEmployee: Int,
    @SerializedName("IsServiceRecordComplete") val isServiceRecordComplete: Boolean,
    @SerializedName("IsSignedByEmployee") val isSignedByEmployee: Int,
    @SerializedName("Level1") val level1: Int,
    @SerializedName("Level2") val level2: Int,
    @SerializedName("LinkTaskName") val linkTaskName: Any,
    @SerializedName("LinkedClientAddress1") val linkedClientAddress1: Any,
    @SerializedName("LinkedClientAddress2") val linkedClientAddress2: Any,
    @SerializedName("LinkedClientCellPhone") val linkedClientCellPhone: Any,
    @SerializedName("LinkedClientCity") val linkedClientCity: Any,
    @SerializedName("LinkedClientFirstName") val linkedClientFirstName: Any,
    @SerializedName("LinkedClientHomePhone") val linkedClientHomePhone: Any,
    @SerializedName("LinkedClientID") val linkedClientID: Int,
    @SerializedName("LinkedClientLastName") val linkedClientLastName: Any,
    @SerializedName("LinkedClientNickName") val linkedClientNickName: Any,
    @SerializedName("LinkedClientOtherPhone") val linkedClientOtherPhone: Any,
    @SerializedName("LinkedClientProfilePic") val linkedClientProfilePic: Any,
    @SerializedName("LinkedClientState") val linkedClientState: Any,
    @SerializedName("LinkedClientZip") val linkedClientZip: Any,
    @SerializedName("LinkedSchedules") val linkedSchedules: List<LinkedSchedulesItem>,
    @SerializedName("MealBreakHours") val mealBreakHours: Double,
    @SerializedName("MealIn") val mealIn: String,
    @SerializedName("MealOut") val mealOut: String,
    @SerializedName("Mileage") val mileage: Double,
    @SerializedName("Modify_DateTime") val modifyDateTime: Any,
    @SerializedName("Modify_UserUID") val modifyUserUID: Int,
    @SerializedName("NoClockInNotified") val noClockInNotified: Int,
    @SerializedName("NoClockOutNotified") val noClockOutNotified: Int,
    @SerializedName("OTExemptHours") val oTExemptHours: Any,
    @SerializedName("OTExemptType") val oTExemptType: Any,
    @SerializedName("Objective") val objective: String,
    @SerializedName("OriginalEndDate") val originalEndDate: Any,
    @SerializedName("OriginalEndTime") val originalEndTime: Any,
    @SerializedName("OriginalStartDate") val originalStartDate: Any,
    @SerializedName("OriginalStartTime") val originalStartTime: Any,
    @SerializedName("OvertimeHours") val overtimeHours: Any,
    @SerializedName("PayPeriodIsFinalized") val payPeriodIsFinalized: Boolean,
    @SerializedName("RecordType") val recordType: String,
    @SerializedName("RecurrenceException") val recurrenceException: Any,
    @SerializedName("RecurrenceId") val recurrenceId: Any,
    @SerializedName("RecurrenceRule") val recurrenceRule: Any,
    @SerializedName("RegularHours") val regularHours: Any,
    @SerializedName("RevisionAction") val revisionAction: Any,
    @SerializedName("RevisionComments") val revisionComments: Any,
    @SerializedName("RevisionReason") val revisionReason: Any,
    @SerializedName("SchedDate") val schedDate: String?,
    @SerializedName("SchedDateEnd") val schedDateEnd: String?,
    @SerializedName("SchedHeadUID") val schedHeadUID: Int,
    @SerializedName("SelectedDate") val selectedDate: String?,
    @SerializedName("ServiceNotes") val serviceNotes: String?,
    @SerializedName("ServiceRecordStatus") val serviceRecordStatus: Int,
    @SerializedName("ShiftFromClock") val shiftFromClock: Int,
    @SerializedName("ShiftMethod") val shiftMethod: Int,
    @SerializedName("ShiftTopValue") val shiftTopValue: Double,
    @SerializedName("ShowInClock") val showInClock: Int,
    @SerializedName("SleepHours") val sleepHours: String,
    @SerializedName("SleepShift") val sleepShift: Int,
    @SerializedName("StaffFirstName") val staffFirstName: String,
    @SerializedName("StaffLastName") val staffLastName: String,
    @SerializedName("StaffSchedUID") val staffSchedUID: Int,
    @SerializedName("StaffShiftName") val staffShiftName: Any,
    @SerializedName("StaffUID") val staffUID: Int,
    @SerializedName("StartTime") val startTime: String,
    @SerializedName("StartTimeActual") val startTimeActual: String,
    @SerializedName("TaskName") val taskName: String,
    @SerializedName("TrackShiftRevision") val trackShiftRevision: Boolean,
    @SerializedName("TravelFrom") val travelFrom: String,
    @SerializedName("TravelTo") val travelTo: String,
    @SerializedName("TravelTo2") val travelTo2: String,
    @SerializedName("TravelTo3") val travelTo3: String,
    @SerializedName("TravelTo4") val travelTo4: String,
    @SerializedName("TravelTo5") val travelTo5: String,
    @SerializedName("TravelTo6") val travelTo6: String,
    @SerializedName("UID") val uID: Int,
    @SerializedName("WorkweekAction") val workweekAction: Int,
    var topMargin: Double?,
    var buttonHeight: Int?,
    var buttonBackground: String?,
    var buttonForeground: String?,
    var title: String?,
    var tempStartTime: String?,
    var tempEndTime: String?,
    var tempSchedDate: String?,
    var tempSchedDateEnd: String?,
) : java.io.Serializable, Cloneable {

    @Throws(CloneNotSupportedException::class)
    public override fun clone(): Any {
        return super.clone()
    }
}