package com.quicksolveplus.authentication.models

import com.google.gson.annotations.SerializedName
import java.io.Serializable

data class User(
    @SerializedName("agencyName") val agencyName: String,
    @SerializedName("allowOpenWorkWeeks") val allowOpenWorkWeeks: Boolean,
    @SerializedName("attestationStatement") val attestationStatement: String,
    @SerializedName("branchOffices") val branchOffices: List<BranchOffice>,
    @SerializedName("canAccessClock") val canAccessClock: Boolean,
    @SerializedName("canAccessDevice") val canAccessDevice: Boolean,
    @SerializedName("canAccessQSMed") val canAccessQSMed: Boolean,
    @SerializedName("canAddClientServiceRecordPhoto") val canAddClientServiceRecordPhoto: Boolean,
    @SerializedName("canConfigureClients") val canConfigureClients: Boolean,
    @SerializedName("covidComplianceFormDetails") var covidComplianceFormDetails: CovidComplianceFormDetails,
    @SerializedName("disableObjectiveShiftTimeCheck") val disableObjectiveShiftTimeCheck: Boolean,
    @SerializedName("disableQSClockOnTimeOption") val disableQSClockOnTimeOption: Boolean,
    @SerializedName("disableQSClockShiftCreation") val disableQSClockShiftCreation: Boolean,
    @SerializedName("displayPstInQSMobile") val displayPstInQSMobile: Boolean,
    @SerializedName("dsnRequireClockIn") val dsnRequireClockIn: Boolean,
    @SerializedName("dsnStartDate") val dsnStartDate: String,
    @SerializedName("earlyLateClock") val earlyLateClock: Int,
    @SerializedName("electronicTimesheet") val electronicTimesheet: Boolean,
    @SerializedName("employeePhoto") val employeePhoto: String,
    @SerializedName("employeeSignature") val employeeSignature: String,
    @SerializedName("enableAttendanceTracking") val enableAttendanceTracking: Boolean,
    @SerializedName("enableDsnInQSMobile") val enableDsnInQSMobile: Boolean,
    @SerializedName("enableTestingForNoBooster") val enableTestingForNoBooster: Boolean,
    @SerializedName("hasSubmittedBooster") var hasSubmittedBooster: Boolean,
    @SerializedName("hasSubmittedExemption") var hasSubmittedExemption: Boolean,
    @SerializedName("hasSubmittedVaccination") var hasSubmittedVaccination: Boolean,
    @SerializedName("includeDSNSummaryField") val includeDSNSummaryField: Boolean,
    @SerializedName("isCompCoinCompany") val isCompCoinCompany: Boolean,
    @SerializedName("isWorkingRemotely") val isWorkingRemotely: Boolean,
    @SerializedName("message") val message: String,
    @SerializedName("message2") val message2: String,
    @SerializedName("noClockInConsecutive") val noClockInConsecutive: Int,
    @SerializedName("noClockInLimit") val noClockInLimit: Int,
    @SerializedName("noClockInLock") val noClockInLock: Int,
    @SerializedName("noClockOutConsecutive") val noClockOutConsecutive: Int,
    @SerializedName("noClockOutLimit") val noClockOutLimit: Int,
    @SerializedName("noClockOutLock") val noClockOutLock: Int,
    @SerializedName("noteCompletionRequired") val noteCompletionRequired: Boolean,
    @SerializedName("openShiftsAvailable") val openShiftsAvailable: Int,
    @SerializedName("overrideRestrictOneEmployeePerClient") val overrideRestrictOneEmployeePerClient: String,
    @SerializedName("passwordChangeDate") val passwordChangeDate: String,
    @SerializedName("passwordUpdateDays") val passwordUpdateDays: Int,
    @SerializedName("passwordUpdateEnabled") val passwordUpdateEnabled: Boolean,
    @SerializedName("requireClientDSNSignature") val requireClientDSNSignature: Boolean,
    @SerializedName("requireClockInPicture") val requireClockInPicture: Boolean,
    @SerializedName("requireClockOutPicture") val requireClockOutPicture: Boolean,
    @SerializedName("requireEmployeeDSNSignature") val requireEmployeeDSNSignature: Boolean,
    @SerializedName("restrictDSN") val restrictDSN: Boolean,
    @SerializedName("restrictDSNHours") val restrictDSNHours: Int,
    @SerializedName("restrictEarlyClockIn") val restrictEarlyClockIn: Boolean,
    @SerializedName("restrictEarlyClockOut") val restrictEarlyClockOut: Boolean,
    @SerializedName("restrictOneEmployeePerClient") val restrictOneEmployeePerClient: Boolean,
    @SerializedName("revisionHistoryIsEnabled") val revisionHistoryIsEnabled: Boolean,
    @SerializedName("securityLevel") val securityLevel: Int,
    @SerializedName("shiftHourLimit") val shiftHourLimit: String,
    @SerializedName("showCovidFormFeature") val showCovidFormFeature: Boolean,
    @SerializedName("showTestingResult") val showTestingResult: Boolean,
    @SerializedName("showTimeSheetDashboard") val showTimeSheetDashboard: Boolean,
    @SerializedName("success") val success: String,
    @SerializedName("testingNoBoosterStartDate") val testingNoBoosterStartDate: String,
    @SerializedName("trackGpsInClockNotification") val trackGpsInClockNotification: Boolean,
    @SerializedName("UID") val uID: Int,
    @SerializedName("userGender") val userGender: String,
    @SerializedName("userLevel1") val userLevel1: Int,
    @SerializedName("userLevel2") val userLevel2: Int,
    @SerializedName("userPermissions") val userPermissions: List<UserPermission>,
    @SerializedName("userRoleName") val userRoleName: String,
    @SerializedName("userRoles") val userRoles: List<String>,
    @SerializedName("viewQSMedClientCaseload") val viewQSMedClientCaseload: Boolean
) : Serializable